[package]
name = "art"
version = "0.1.2"
authors = ["Tumypmyp"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
dioxus = { version = "0.7.0-rc.0", features = ["router"] }
# dioxus-liveview = { version = "0.7.0-rc.0" }
# dioxus-server = { version = "0.7.0-rc.0" }
dioxus-web = { version = "0.7.0-rc.0" }
tokio = { version = "1.46.1", default-features = false, features = ["macros", "rt"] }
three-d = { version = "0.18.2" }
web-sys = { version = "0.3", features = ["HtmlCanvasElement", "Window"] }

[features]
default = ["web"]
# The feature that are only required for the web = ["dioxus/web"] build target should be optional and only enabled in the web = ["dioxus/web"] feature
web = ["dioxus/web"]
# The feature that are only required for the desktop = ["dioxus/desktop"] build target should be optional and only enabled in the desktop = ["dioxus/desktop"] feature
desktop = ["dioxus/desktop"]
# The feature that are only required for the mobile = ["dioxus/mobile"] build target should be optional and only enabled in the mobile = ["dioxus/mobile"] feature
mobile = ["dioxus/mobile"]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"

[build]
target-dir = "target"
output-dir = "target"
