name: Dioxus build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    # - name: Install binstall
    #   run: cargo install cargo-binstall
    
    - name: Install dx
      run: cargo install --git https://github.com/DioxusLabs/dioxus dioxus-cli --locked
    
    - name: Build site
      run: dx bundle --out-dir build --platform web --ssg

    - name: check1
      run: git status
      
    - name: Build site2
      run: dx bundle --out-dir build --platform web --ssg

    - name: check2
      run: git status

    - name: Create 404.html
      run: cp build/public/index.html build/public/404.html
    
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: build/public