name: Dioxus build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    # - name: Install binstall
    #   run: cargo install cargo-binstall
    
    # - name: Binstall dx
    #   run: cargo binstall dioxus-cli
    
    # - name: Build site
    #   run: dx bundle --out-dir docs --platform web --ssg

    - name: Create 404.html
      run: cp docs/public/index.html docs/public/404.html
    
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: docs/public